AppBundle\Entity\Bet:
    type: entity
    table: bet
    uniqueConstraints:
        UNIQ_D044D5D4A76ED395:
            columns:
                - user_id
    id:
        idIncrement:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_increment
            generator:
                strategy: IDENTITY
    fields:
        matchkey:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: matchKey
        teamHome:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: team_home
        teamAway:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: team_away
        teamHomeScore:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: team_home_score
        teamAwayScore:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: team_away_score
        token:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        created:
            type: datetime
            nullable: false
        updated:
            type: datetime
            nullable: true
        active:
            type: boolean
            nullable: false
    manyToOne:
        user:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
