AppBundle\Entity\CategoryHasProduct:
    type: entity
    table: category_has_product
    indexes:
        fk_category_has_product_product1_idx:
            columns:
                - product_id
        fk_category_has_product_category1_idx:
            columns:
                - category_id
    id:
        idIncrement:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_increment
            generator:
                strategy: IDENTITY
    fields:
        stock:
            type: integer
            nullable: true
            options:
                unsigned: false
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
    manyToOne:
        category:
            targetEntity: Category
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                category_id:
                    referencedColumnName: id_increment
            orphanRemoval: false
        product:
            targetEntity: Product
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                product_id:
                    referencedColumnName: id_increment
            orphanRemoval: false
    lifecycleCallbacks: {  }
