AppBundle\Entity\Course:
    type: entity
    table: course
    id:
        idIncrement:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_increment
            generator:
                strategy: IDENTITY
    fields:
        code:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        name:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        isActive:
            type: boolean
            nullable: true
            column: is_active
    manyToMany:
        exam:
            targetEntity: Exam
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: course
            joinTable:
                name: course_has_exam
                joinColumns:
                    -
                        name: course_id
                        referencedColumnName: id_increment
                inverseJoinColumns:
                    -
                        name: exam_id
                        referencedColumnName: id_increment
            orderBy: null
        user:
            targetEntity: UserTianos
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: course
            joinTable:
                name: course_has_user
                joinColumns:
                    -
                        name: course_id
                        referencedColumnName: id_increment
                inverseJoinColumns:
                    -
                        name: user_id
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }
