AppBundle\Entity\GroupOfUsers:
    type: entity
    table: group_of_users
    id:
        idIncrement:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_increment
            generator:
                strategy: IDENTITY
    fields:
        groupName:
            type: string
            nullable: false
            length: 150
            options:
                fixed: false
            column: group_name
        slug:
            type: string
            nullable: false
            length: 150
            options:
                fixed: false
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        isActive:
            type: boolean
            nullable: true
            options:
                default: '1'
            column: is_active
    manyToMany:
        user:
            targetEntity: UserTianos
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: groupOfUsers
            joinTable:
                name: group_of_users_has_user
                joinColumns:
                    -
                        name: group_of_users_id
                        referencedColumnName: id_increment
                inverseJoinColumns:
                    -
                        name: user_id
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }
