AppBundle\Entity\PointOfSaleHasProduct:
    type: entity
    table: point_of_sale_has_product
    indexes:
        fk_point_of_sale_has_product_product1_idx:
            columns:
                - product_id
        fk_point_of_sale_has_product_point_of_sale1_idx:
            columns:
                - point_of_sale_id
    id:
        idIncrement:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_increment
            generator:
                strategy: IDENTITY
    fields:
        stock:
            type: integer
            nullable: true
            options:
                unsigned: false
        stockMin:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: stock_min
        stockMax:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: stock_max
        description:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
    manyToOne:
        product:
            targetEntity: Product
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                product_id:
                    referencedColumnName: id_increment
            orphanRemoval: false
        pointOfSale:
            targetEntity: PointOfSale
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                point_of_sale_id:
                    referencedColumnName: id_increment
            orphanRemoval: false
    lifecycleCallbacks: {  }
