AppBundle\Entity\Profile:
    type: entity
    table: profile
    id:
        idIncrement:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_increment
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        slug:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        isActive:
            type: boolean
            nullable: true
            column: is_active
    manyToMany:
        role:
            targetEntity: Role
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: profile
            joinTable:
                name: profile_has_role
                joinColumns:
                    -
                        name: profile_id
                        referencedColumnName: id_increment
                inverseJoinColumns:
                    -
                        name: role_id
                        referencedColumnName: id_increment
            orderBy: null
    lifecycleCallbacks: {  }
