AppBundle\Entity\ReportPointOfSaleAndProduct:
    type: entity
    table: report_point_of_sale_and_product
    indexes:
        fk_report_point_of_sale_and_product_point_of_sale_has_produ_idx:
            columns:
                - point_of_sale_has_product_id
    id:
        idIncrement:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_increment
            generator:
                strategy: IDENTITY
    fields:
        timeDelivery:
            type: datetime
            nullable: true
            column: time_delivery
        stockOut:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: stock_out
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        isActive:
            type: boolean
            nullable: false
            column: is_active
    manyToOne:
        pointOfSaleHasProduct:
            targetEntity: PointOfSaleHasProduct
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                point_of_sale_has_product_id:
                    referencedColumnName: id_increment
            orphanRemoval: false
    lifecycleCallbacks: {  }
