AppBundle\Entity\Reserva:
    type: entity
    table: reserva
    indexes:
        fk_reserva_point_of_sale1_idx:
            columns:
                - point_of_sale_id
    id:
        idIncrement:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_increment
            generator:
                strategy: IDENTITY
    fields:
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        isActive:
            type: boolean
            nullable: true
            column: is_active
        inicio:
            type: datetime
            nullable: true
        fin:
            type: datetime
            nullable: true
        time:
            type: string
            nullable: true
            length: 80
            options:
                fixed: false
        name:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        userId:
            type: string
            nullable: true
            length: 11
            options:
                fixed: false
            column: user_id
    manyToOne:
        pointOfSale:
            targetEntity: PointOfSale
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                point_of_sale_id:
                    referencedColumnName: id_increment
            orphanRemoval: false
    lifecycleCallbacks: {  }
