AppBundle\Entity\UserTianos:
    type: entity
    table: user_tianos
    indexes:
        FK_8D93D649CCFA12B8:
            columns:
                - profile_id
    uniqueConstraints:
        email_UNIQUE:
            columns:
                - email
        username_UNIQUE:
            columns:
                - username
        dni_UNIQUE:
            columns:
                - dni
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        clientId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: client_id
        username:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        slug:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        deviceCode:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: device_code
        password:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        salt:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        dni:
            type: string
            nullable: true
            length: 8
            options:
                fixed: false
        name:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        lastName:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: last_name
        dob:
            type: date
            nullable: true
        address:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        email:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        phone:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        image:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        isActive:
            type: boolean
            nullable: false
            options:
                default: '1'
            column: is_active
        lastAccess:
            type: datetime
            nullable: true
            column: last_access
    manyToOne:
        profile:
            targetEntity: Profile
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                profile_id:
                    referencedColumnName: id_increment
            orphanRemoval: false
    manyToMany:
        course:
            targetEntity: Course
            cascade: {  }
            fetch: LAZY
            mappedBy: user
            inversedBy: null
            joinTable: null
            orderBy: null
        groupOfUsers:
            targetEntity: GroupOfUsers
            cascade: {  }
            fetch: LAZY
            mappedBy: user
            inversedBy: null
            joinTable: null
            orderBy: null
        files:
            targetEntity: Files
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: user
            joinTable:
                name: user_has_files
                joinColumns:
                    -
                        name: user_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: files_id
                        referencedColumnName: id_increment
            orderBy: null
    lifecycleCallbacks: {  }
